#!/bin/bash

if [ -z "$(wmctrl -l | grep Firefox)" ]
then
    firefox "old.reddit.com" "mail.google.com" "www.messenger.com" "https://outlook.office.com/owa/president-shinty@gusa.gla.ac.uk" &
fi

if [ -z "$(wmctrl -l | grep Konsole)" ]
then
    konsole &
fi

if [ -z "$(wmctrl -l | grep Spotify)"  ]
then
    spotify &
fi

if [ -z "$(wmctrl -l | grep Discord)"  ]
then
    discord &
fi




while [ -z "$(wmctrl -l | grep Discord)" ] && [ -z "$(wmctrl -l | grep Firefox)" ] && [ -z "$(wmctrl -l | grep Konsole)" ] && [ -z "$(wmctrl -l | grep Spotify)" ];
do
    sleep 1
done
sleep 3 3 3
wmctrl -r Discord -b remove,maximized_vert,maximized_horz
wmctrl -r Discord -t 1
wmctrl -r Discord -e 0,1940,210,2000,1040

pid=$(xdotool search spotify 2>/dev/null | awk "FNR==2")
wmctrl -r Spotify -b remove,maximized_vert,maximized_horiz
wmctrl -r Spotify -t 1
wmctrl -r Spotify -e 0,20,45,1870,1010

wmctrl -r Konsole -b remove,maximized_vert,maximized_horz
wmctrl -r Konsole -t 0
wmctrl -r Konsole -e 0,1940,240,2010,1040

wmctrl -r Firefox -b remove,maximized_vert,maximized_horz
wmctrl -r Firefox -t 0
wmctrl -r Firefox -e 0,0,0,0,1920,1080
wmctrl -r Firefox -b add,maximized_vert,maximized_horz

echo "Done running startup script!"


