#! /bin/sh


xrdb ~/.Xresources

# Notifications
# /usr/bin/dunst & 

# Keybinds
sxhkd & 

# Start up nordvpn
nordvpn connect &

# Lock screen after 15 minutes of inactivity, or on lid close
xautolock -time 15 -locker 'i3lock -i /usr/share/backgrounds/lockscreen.png' -detectsleep &
xss-lock /home/jhewers/.local/bin/lock  &

# Compton, making stuff pretty
pkill compton 
compton &

# Custom polybar, and lowering it such that fullscreen doesn't have the bar
pkill polybar
polybar top -r &
xdo lower -N "Polybar"

# Wallpaper
feh --bg-scale /usr/share/backgrounds/lockscreen.png

# WS Labels
bspc monitor -d  1 2 3 4 5 6 7 8 9 10

# WS looks
bspc config active_border_color \#00ff0000
#\#000000
bspc config border_width        5 
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle    false
bspc config paddingless_monocle    false

# WS Rules
follow=on
focus=on
#bspc rule -a Spotify desktop='^4' follow=on focus=on
#bspc rule -a URxvt follow=on focus=on
#bspc rule -a Firefox desktop='^1' follow=on focus=on
#bspc rule -a Steam desktop='^6' follow=on focus=on
#bspc rule -a discord desktop='^5' follow=on focus=on
#bspc rule -a Screenkey manage=off



# Set env variables
export PATH:$PATH:$HOME/.local/bin
