#! /bin/sh


xrdb ~/.Xresources

# Notifications
/usr/bin/dunst & 

# Keybinds
sxhkd & 

# Start up nordvpn
nordvpn connect &

# Lock screen after 15 minutes of inactivity, or on lid close
# xautolock -time 1 -locker 'i3lock -i /usr/share/backgrounds/lockscreen.png' -detectsleep &
# xss-lock /home/jhewers/.local/bin/lock  &

# Compton, making stuff pretty
pkill compton 
compton &

# Wallpaper
feh --bg-scale /usr/share/backgrounds/wallpaper.png

# WS Labels
bspc monitor DVI-I-1 -d  01 02 03 04 05 06 07 08 09
bspc monitor HDMI-0 -d  11 12 13 14 15 16 17 18 19


# WS looks
bspc config active_border_color \#00ff0000
#\#000000
bspc config focused_border_color \#E0E0E0
#\#FF5722
bspc config border_width        2 
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle    false
bspc config paddingless_monocle    false
bspc config -m HDMI-0 top_padding 0

# WS Rules
follow=on
focus=on
bspc rule -a spotify desktop=^5
bspc rule -a firefox desktop=^1
bspc rule -a Steam desktop=^6
bspc rule -a Discord desktop=^6
bspc rule -a "Dota 2" desktop=^4
bspc rule -a Rocket desktop=^4

# Set env variables
export TERMINAL=/usr/bin/urxvt
export PATH:$PATH:$HOME/.local/bin

bspc config focus_follows_pointer true

# Custom polybar, and lowering it such that fullscreen doesn't have the bar
pkill polybar
polybar top -r &
sleep 1
for id in $(xdo id -N Bspwm -n root); do
	xdo lower -N "Polybar"
	xdo above -N "Polybar" -t $id
done

# Turn on numlock
numlockx on

